---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.26.0
    env:
      TZ: ${TIMEZONE}
      ZIGBEE2MQTT_DATA: /data
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: mosquitto
        user: "${SECRET_MQTT_USERNAME}"
        password: "${SECRET_MQTT_PASSWORD}"
      serial:
        port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2289066-if00
      frontend:
        port: 8080
      experimental:
        new_api: true
    securityContext:
      privileged: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "zigbee.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zigbee.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2289066-if00
        hostPathType: CharDevice
