apiVersion: v1
kind: Service
metadata:
  name: eufy-security-ws
  namespace: home
  labels:
    run: eufy-security-ws
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: eufy-security-ws
