apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.12.3
    env:
      TZ: America/NewYork
    #envFrom:
    #- secretRef:
    #    name: home-assistant-env

    # hostNetwork: true
    # dnsPolicy: ClusterFirstWithHostNet

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
