apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.11.4
    env:
      TZ: America/NewYork
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "home.jw2.org"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: home-tls
            hosts:
              - "home.jw2.org"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      usb:
        enabled: true
        type: hostPath
        hostPath: /run/dbus
