---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_K8S_GATEWAY_ADDR: 172.16.0.80
  METALLB_LB_RANGE: 172.16.0.85-172.16.0.89
  METALLB_INGRESS_ADDR: 172.16.0.81
  SVC_HOME_ASSISTANT_ADDR: 172.16.0.88
  SVC_MOSQUITTO_ADDR: 172.16.0.89
