---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: house
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 15.2.38
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/wordpress
      tag: 5.9.2-debian-10-r2
      debug: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: "house.${SECRET_DOMAIN}"
      tls: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
    persistence:
      storageClass: nfs-client
    mariadb:
      enabled: true
      debug: true
      auth:
        rootPassword: "${HOUSE_MARIADB_AUTH_ROOTPASSWORD}"
        database: house
        username: "${HOUSE_WORDPRESS_USERNAME}"
        password: "${HOUSE_WORDPRESS_PASSWORD}"
      primary:
        persistence:
          storageClass: nfs-client
          size: 10Gi
    wordpressScheme: https
