---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 6.2.0
    env:
      TZ: "America/New_York"
    securityContext:
      privileged: true
    resources:
      requests:
        memory: 200Mi
        cpu: 50m
      limits:
        memory: 500Mi
    service:
      main:
        ports:
          websockets:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: "z.jw2.org"
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        emptyDir:
          enabled: false
        mountPath: /usr/src/app/store
        accessMode: ReadWriteOnce
        size: "1Gi"
        skipuninstall: true
      usb:
        enabled: true
        type: hostPath
        hostPath: '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10 700_Z-Wave_Stick_0001-if00-port0'
        hostPathType: CharDevice
