# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Zhqu8OCmeg==,iv:xNLYtWuu1HAa6I3EmM67sb/ktKbAIS8iEa4FXSgHs54=,tag:TC1j3WHmwkCdYY4aRMirnw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9z+i3rcvEo2dX8S7AbCvMl0d+w==,iv:Qp70qsPJ7OA90R3sMp1MSgWY0ssRygq8cl0QNE+b13Q=,tag:1ekB3rFbT0zOP8RHiN3bUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7y3d5lw36h8wzlakr9dtdea0s0tawd245nvdpqjlvfs0sgdzsmsqxyzg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcUVTN3NUZDYwbi9STVph
            T2pRTVpRR3d5ZEVYNURPeUdMTE41WXgzUUN3CkVlQWhxQXNYN0x1SENmTG51Vksz
            RkxmVUdES3FNcGFzbzF0S1dzUzRYa3MKLS0tIDBsK3o3c2lTZFlNOFAza2p4U1BH
            WitQU3hpSlNsWGlyZ0UyVTdwejgzMlUKitYjmkuuiaI4f+Dms/KrJzjXcZYYIFzg
            8RzdrdkGYYMLTAquIum0Qswa/o7Z/ISmU/og1wgr1R/ljkXfV5w73w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T05:04:31Z"
    mac: ENC[AES256_GCM,data:yHh/lCe+UHtWTSU6wdhzFrgSLxo/2Sh+l/F4TNBqSynZmwxeUl6EFrw8bluNeLvUbOrfEUXwK1IJWrlK9N6v7seSMJcIoID0rgom7LZkMvfkdD0r89aElN4CAdeaPUbl7HiIs3ZTFl8rU8fttiKE28kvS29KHpvkONwbG21L58Y=,iv:B7hiYKLJMWJBZKj5+sgobcO6li2CmyRjXpBExM76rEI=,tag:0KMG+mbLOM//GY3tbPMLfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
