---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.16.0.85-172.16.0.89
  METALLB_TRAEFIK_ADDR: 172.16.0.85
  SVC_HOME_ASSISTANT_ADDR: 172.16.0.88
