---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.10.1-amd64
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN}"
            secretName: frigate-tls
    securityContext:
      privileged: true
    persistence:
      data:
        enabled: true
        existingClaim: frigate-config-v1
        mountPath: /data
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume1/frigate
        mountPath: /media
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm
    config: |
      mqtt:
        host: mosquitto
        topic_prefix: frigate
        user: ${SECRET_MQTT_USERNAME}
        password: ${SECRET_MQTT_PASSWORD}

      database:
        path: /data/frigate.db

      # detectors:
      #   coral:
      #     type: edgetpu
      #     device: usb

      # Global objects configuration
      objects:
         track:
           - person
           - dog
           - cat
           - car
           - bicycle
      #   filters:
      #     person:
      #       min_area: 2500
      #       max_area: 100000
      #       threshold: 0.7

      birdseye:
        mode: objects
        quality: 4

      # Global ffmpeg configuration
      ffmpeg:
        hwaccel_args:
          - -hwaccel
          - vaapi
          - -hwaccel_device
          - /dev/dri/renderD128
          - -hwaccel_output_format
          - yuv420p
        output_args:
          record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

      # Global recording options
      record:
        enabled: True
        retain:
          days: 14
          mode: motion
        events:
          retain:
            default: 14
            mode: motion
      snapshots:
        enabled: True
        timestamp: False
        retain:
          default: 14

      # Cameras
      cameras:
        backyard:
          ffmpeg:
            inputs:
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-backyard.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-backyard.${SECRET_DOMAIN}/live
                roles:
                  - record
          detect:
            width: 1280
            height: 720
            fps: 10
        driveway:
          ffmpeg:
            inputs:
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-driveway.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-driveway.${SECRET_DOMAIN}/live
                roles:
                  - record
          detect:
            width: 1280
            height: 720
            fps: 10
        porch:
          ffmpeg:
            inputs:
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-porch.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-porch.${SECRET_DOMAIN}/live
                roles:
                  - record
          detect:
            width: 1280
            height: 720
            fps: 10
        front:
          ffmpeg:
            inputs:
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-front.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-front.${SECRET_DOMAIN}/live
                roles:
                  - record
          detect:
            width: 1280
            height: 720
            fps: 10
        side-garage:
          ffmpeg:
            inputs:
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-sidegarage.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
                  - rtmp
              - path: rtsp://view:${FRIGATE_RTSP_PASSWORD}@cam-sidegarage.${SECRET_DOMAIN}/live
                roles:
                  - record
          detect:
            width: 1280
            height: 720
            fps: 10
          zones:
            neighbors_driveway:
              coordinates: 0,0,0,424,719,0
              objects:  # everything but cars
                - person
                - dog
                - cat
                - bicycle
            my_driveway:
              coordinates: 716,0,1280,0,971,720,0,720,0,422
        doorbell:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${FRIGATE_DOORBELL_PASSWORD}@doorbell.${SECRET_DOMAIN}/cam/realmonitor?channel=1&subtype=1&authbasic=64
                roles:
                  - detect
                  - rtmp
              - path: rtsp://admin:${FRIGATE_DOORBELL_PASSWORD}@doorbell.${SECRET_DOMAIN}/
                roles:
                  - record
          objects:
            track:
              - person
              - dog
              - cat
              - bicycle
          detect:
            width: 720
            height: 576
            fps: 10

    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate-config"
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/custom-coral-tpu
    #               operator: In
    #               values:
    #                 - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        memory: 500Mi
        cpu: 1000m
      limits:
        gpu.intel.com/i915: 1
        memory: 3000Mi
