---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smokeping
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts
      chart: smokeping
      version: 0.1.24
      sourceRef:
        kind: HelmRepository
        name: smokeping
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/New_York"
    securityContext:
      privileged: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
      - host: "ping.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
        - hosts:
            - "ping.${SECRET_DOMAIN}"
          secretName: smokeping-tls
    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
      data:
        enabled: true
        emptyDir: false
        mountPath: /data
        accessMode: ReadWriteOnce
        size: "1Gi"
 
