# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:XjK0KbXZM8ErCE9HEzBgGIJbpV2VFZ2XrtiJb5eTMZ9TYTn+kA==,iv:kYdmwPWIsv6hcVCV76Y5ggXft/2NQh4BCPNnkCgsnqY=,tag:k0VEKjpB4xWj687ksE1oJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7y3d5lw36h8wzlakr9dtdea0s0tawd245nvdpqjlvfs0sgdzsmsqxyzg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeUJvSTduUS9YSE9uQnli
            Q2l2UXB1ajBaNHpwcmVBNXVWZ2NFY0ZPbVJRCldtOVRsSjZidSs4a01Jc2FyWTVn
            dWxJMkg1dFVPbG52b3gyU3J0UERxVXcKLS0tIGNLcTk5amtkWXUvaklwUWNCNDlp
            cGFtcFkyS01URlQ4WXdIZmtPTzBFQUUKfuJPNZZpfKYUxsDoeD+IQmhcE9dIdkQ4
            6LehrytTxk+2U9K3SSldhL3mIP4mJA6+mfHERLPxa/YCR/19202hrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T04:22:06Z"
    mac: ENC[AES256_GCM,data:CUjJBA0gGXSuJmI7N4FwrepYqeLzwRUyXTaoL6zLrbO43CnGq7Uim8Oc77iVP56RE2B45Vkj1E04wqZnpxcAxYAuyhcOVrDmU891MYci//LX34WMuAz9Ew1biufuZy+FvIKxSkzbOoLuB6A1L09ORyub1zp2nyhgzWCSXSClVfw=,iv:kCRGzf/UQghMUJmZ1Yc21Kg4c2RwJZJVDen8nvdJUhE=,tag:N3jZCfIiRR2NK9/zmno/5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
